# Generated by Django 4.1.5 on 2023-01-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="menuitem", old_name="Category", new_name="category",
        ),
    ]
